version: '3.8'

networks:
  app-network:

volumes:
  app-data:

services:
  db:
    image: mariadb:10.5
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "7340458"
      MYSQL_DATABASE: midatabase
      MYSQL_USER: taoista
      MYSQL_PASSWORD: "7340458"
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 7340458 
    networks:
      - app-network

  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserver-luisolave
    restart: unless-stopped
    ports:
      - "8005:8080"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network

  backend:
    build:
      context: .docker/php
      dockerfile: dockerfile
    container_name: luisolave-backend
    volumes:
      - ./:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
